id: P001844
initial_creation_type: ocr
created_at: 31/03/2020
last_modified_at: 2021-12-17 10:25:23.936258
source_metadata:
  id: bdr:W29655
  title: དྲང་ངེས་བློ་བཟང་དགོངས་གསལ་དང་ཚད་མ་གཞན་ཕན་རྒྱ་མཚོ་བཅས།
  author: ''
  volumes:
    a0596239b7684929a49e0b1a2861381a:
      image_group_id: I1KG10298
      title: ''
      volume_number: 1
      total_pages: 193
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
