id: P001844
initial_creation_type: ocr
source_metadata:
  id: bdr:W29655
  title: དྲང་ངེས་བློ་བཟང་དགོངས་གསལ་དང་ཚད་མ་གཞན་ཕན་རྒྱ་མཚོ་བཅས།
  author: ''
  volumes:
    a0596239b7684929a49e0b1a2861381a:
      image_group_id: I1KG10298
      title: ''
      volume_number: 1
      total_pages: 193
